### ISSUE TITLE
investigate STAC items for transform functions

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/csv2bufr#28]
`csv2bufr.transform` returns a dictionary of messages, each of which having a `_meta` object to emit some metadata about the messages.  We should consider using the [STAC item specification](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md).

At some point having this metadata when `csv2bufr.transform` returns will be valuable for both wis2node processing and even MQP notifications to support downstream monitoring/metrics/reporting applications.

cc @efucile

**Comment by david-i-berry** [comment]
@tomkralidis is this still something we want to do?

**Comment by tomkralidis** [comment]
IMO this would still be valuable, to at least update to a GeoJSON feature, for interoperabilty.  Happy to implement this once #80 is addressed.

**Comment by tomkralidis** [comment]
Implemented as GeoJSON in #83
